language: node_js

node_js:
  - "4.0.0"
  - "0.12"
  - "0.10.30"

matrix:
  allow_failures:
  - node_js: "4.0.0"

before_install:
  - "sudo apt-get update"
  - "pushd test; make; popd"

script:
  - "make all"
